library: rci: Fix wrong assignments
This commit fixes several assignment issues that appear as of GCC 10
on build, like the following:

| src/rci_state_gps_stats.c:34:41: error: implicit conversion from 'enum <anonymous>'
| to 'ccapi_state_gps_stats_error_id_t' [-Werror=enum-conversion]
|    34 |  ccapi_state_gps_stats_error_id_t ret = CCAPI_GLOBAL_ERROR_NONE;
|       |                                         ^~~~~~~~~~~~~~~~~~~~~~~

https://jira.digi.com/browse/DEL-7418

Signed-off-by: Arturo Buzarra <arturo.buzarra@digi.com>